version: '3.1'

services:
  gollum:
    image: gollum-app:latest
    container_name: gollum
    ports:
      - "4567:4567"
    environment:
      - "GITHUB_REPO_URL=${GITHUB_REPO_URL}"
      - "GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}"
      - "GOLLUM_APP_USE_BRANCH=${GOLLUM_APP_USE_BRANCH}"